(function(g){var window=this;'use strict';var HXa=function(a,b){var c=[];return g.lt(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},q4=function(a,b){return"getAll"in IDBIndex.prototype?g.Zs(a.j.getAll(b,void 0)):HXa(a,b)},IXa=function(a,b){return g.et(a,["captions"],{mode:"readonly",
Kc:!0},function(c){return g.tna(c.objectStore("captions"),b,void 0)})},JXa=function(a){var b=new g.Ex("und",new g.bA("Default","und",!0));
b.captionTracks=a.captionTracks;return b},KXa=function(a){return new g.wi(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},k=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.Oba(m,g.Wa(f,l),k);
else b(e)})},r4=function(a){this.j=a},s4=function(){r4.apply(this,arguments)},t4=function(){s4.apply(this,arguments)},u4=function(){s4.apply(this,arguments)},v4=function(){s4.apply(this,arguments)},w4=function(){r4.apply(this,arguments)},x4=function(){s4.apply(this,arguments)},y4=function(){s4.apply(this,arguments)},z4=function(){s4.apply(this,arguments)},A4=function(){s4.apply(this,arguments)},B4=function(){s4.apply(this,arguments)},C4=function(){s4.apply(this,arguments)},D4=function(){s4.apply(this,
arguments)},E4=function(){s4.apply(this,arguments)},F4=function(){s4.apply(this,arguments)},G4=function(){s4.apply(this,arguments)},H4=function(){s4.apply(this,arguments)},I4=function(){r4.apply(this,arguments)},J4=function(){s4.apply(this,arguments)},K4=function(){s4.apply(this,arguments)},L4=function(){s4.apply(this,arguments)},M4=function(){s4.apply(this,arguments)},N4=function(){s4.apply(this,arguments)},O4=function(){s4.apply(this,arguments)},P4=function(){s4.apply(this,arguments)},Q4=function(){s4.apply(this,
arguments)},R4=function(){s4.apply(this,arguments)},S4=function(){s4.apply(this,arguments)},T4=function(){s4.apply(this,arguments)},U4=function(){s4.apply(this,arguments)},V4=function(){s4.apply(this,arguments)},W4=function(){s4.apply(this,arguments)},LXa=function(a){var b=g.zD();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.Eva(b);JSON.stringify(b);return b},MXa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,g.wt(),2);if(3!=d.j)return(b=d.u)?g.A(d,g.CD(b),3):d.return();c=d.u;return d.return(g.et(c,["index","media","captions"],{mode:"readwrite",Kc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.Xs.all(e).then(function(){})}))})},NXa=function(){var a,b;
return g.B(function(c){if(1==c.j)return g.A(c,g.wt(),2);if(3!=c.j){a=c.u;if(!a)throw g.Vs("rvdfd");return g.A(c,g.CD(a),3)}b=c.u;return c.return(g.et(b,["index","media"],{mode:"readwrite",Kc:!0},function(d){var e={};return g.jt(d.objectStore("index"),{},function(f){var k=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),l=g.Xs.resolve(void 0);if(k){var m=k[1];k=k[2];e[m]=e[m]||{};var n;e[m][k]=g.Kva(null==(n=f.getValue())?void 0:n.fmts)}else l=f.delete().then(function(){});
return g.Xs.all([f.continue(),l]).then(function(p){return g.q(p).next().value})}).then(function(){for(var f={},k=g.q(Object.keys(e)),l=k.next();!l.done;l=k.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=LXa(f);return g.wna(d.objectStore("media"),{},function(p){var r=p.getKey().match(g.Ova);r&&f[r[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},OXa=function(a,b){var c,d;
return g.B(function(e){if(1==e.j)return g.A(e,g.wt(),2);if(3!=e.j){c=e.u;if(!c)throw g.Vs("wct");return g.A(e,g.CD(c),3)}d=e.u;return g.A(e,g.et(d,["captions"],{mode:"readwrite",Kc:!0},function(f){var k=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.ft(f,b[l],a+"|"+b[l].metadata.vss_id);k.push(m)}return g.Xs.all(k)}),0)})},PXa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.A(e,g.wt(),2);if(3!=e.j){c=e.u;if(!c)throw g.Vs("gactfv");return g.A(e,g.CD(c),3)}d=e.u;return e.return(IXa(d,b))})},QXa=function(a){return g.B(function(b){g.BD(a,0);
return b.return(MXa(a))})},RXa=function(a){return{context:g.QH(),
videoIds:a}},X4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},Y4=function(a,b){b=void 0===b?{}:b;
g.Ls.call(this,g.GTa[a],Object.assign({},{name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,Y4.prototype)},SXa=function(a){return new Y4("WRONG_DATA_TYPE",{nU:a})},TXa=function(a){return a instanceof Error?new Y4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new Y4("UNKNOWN_ENCODE_ERROR")},UXa=function(a){return a instanceof Error?new Y4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new Y4("UNKNOWN_DECODE_ERROR")},VXa=function(a,b){a=a instanceof
Y4?a:b(a);
g.S(a);throw a;},WXa=function(){},XXa=function(a,b,c){try{return a.B(b,c)}catch(d){VXa(d,TXa)}},YXa=function(a,b,c){try{return a.u(b,c)}catch(d){VXa(d,UXa)}},Z4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},$4=function(a){this.j=a},a5=function(){},ZXa=function(){this.j={};
this.j[0]=new a5;if(!g.Q("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.Ms();var c=Z4(b);var d=new $4(new g.WB(c),new g.VB(c))}catch(e){throw a=e instanceof Error?new Y4("KEY_CREATION_FAILED",{originalMessage:e.message}):new Y4("KEY_CREATION_FAILED"),g.S(a),a;}a[1]=d}},b5=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new Y4("INVALID_ENCODER_VERSION",{nU:b}),g.S(b),b;return a},aYa=function(a){var b=$Xa[a];
if(b)return b;g.Pv(new g.Ls("Entity model not found.",{entityType:a}))},bYa=function(a){var b=new ZXa,c=a.objectStore("EntityStore"),d=a.objectStore("EntityAssociationStore");
g.jt(c,{},function(e){var f=e.getValue(),k=YXa(b5(b,f.version),f.data,f.key),l=g.PK(f.key).entityType;l=aYa(l);if(!l)return e.continue();l=(new l(k)).fd();k=[];l=g.q(l);for(var m=l.next();!m.done;m=l.next())k.push(g.ft(d,{parentEntityKey:f.key,childEntityKey:m.value}));return g.Xs.all(k).then(function(){return e.continue()})})},cYa=function(){if(c5)return c5();
var a={};c5=g.Kt("PersistentEntityStoreDb",{Mq:(a.EntityStore={Fn:1},a.EntityAssociationStore={Fn:2},a),jy:!1,upgrade:function(b,c,d){c(1)&&g.ht(g.ct(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.ct(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.ht(b,"byParentEntityKey","parentEntityKey"),g.ht(b,"byChildEntityKey","childEntityKey"));c(3)&&!c(1)&&bYa(d)},
version:g.Q("pes_migrate_association_data")?3:2});return c5()},dYa=function(a){return g.ot(cYa(),a)},eYa=function(a,b){this.j=a;
this.u=b;this.B={}},fYa=function(a,b){return YXa(b5(a.u,b.version),b.data,b.key)},d5=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return fYa(a,d)}})},e5=function(a,b,c){return c?(c=c.map(function(d){return d5(a,d,b)}),g.Xs.all(c)):q4(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return fYa(a,e)})})},g5=function(a,b,c){var d=X4(b),e=b5(a.u,1),f={key:d,
entityType:c,data:XXa(e,b,d),version:1};return a.j.objectStore("EntityStore").get(d).then(function(k){if(k&&k.entityType!==c)throw Error("Incorrect entity type");}).then(function(){return g.Xs.all([g.ft(a.j.objectStore("EntityStore"),f),
gYa(a,b,c)])}).then(function(){f5(a,d,c);
return d})},h5=function(a,b,c){b=b.map(function(d){return g5(a,d,c)});
return g.Xs.all(b)},i5=function(a,b,c){if(null==c?0:c.pL){var d=new Set;
return hYa(a,b,d).then(function(){for(var f=[],k=g.q(d),l=k.next();!l.done;l=k.next())f.push(i5(a,l.value));return g.Xs.all(f).then(function(){})})}var e=g.PK(b).entityType;
return g.Xs.all([a.j.objectStore("EntityStore").delete(b),j5(a,b)]).then(function(){f5(a,b,e)})},iYa=function(a,b){return g.lt(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.Xs.all([c.delete(),
j5(a,c.rA())]).then(function(){f5(a,c.rA(),b);return c.continue()})})},jYa=function(a,b,c,d){var e=b5(a.u,1);
return d5(a,b,d).then(function(f){if(f){f=g.AK(f,c,void 0);var k={key:b,entityType:d,data:XXa(e,f,b),version:1};return g.Xs.all([g.ft(a.j.objectStore("EntityStore"),k),gYa(a,f,d)])}}).then(function(){f5(a,b,d);
return b})},f5=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},kYa=function(a,b,c){var d=X4(b);
c=aYa(c);if(!c)return g.Xs.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.q(c.fd());for(var e=c.next();!e.done;e=c.next())b.push(g.ft(a,{parentEntityKey:d,childEntityKey:e.value}));return g.Xs.all(b).then(function(f){return f.map(function(k){return k[1]})})},j5=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},gYa=function(a,b,c){var d=X4(b);
return j5(a,d).then(function(){return kYa(a,b,c)})},hYa=function(a,b,c){if(c.has(b))return g.Xs.resolve(void 0);
c.add(b);return lYa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.Xs.resolve(void 0),f={};
d=g.q(d);for(var k=d.next();!k.done;f={HC:f.HC},k=d.next())f.HC=k.value,e=e.then(function(l){return function(){return hYa(a,l.HC,c)}}(f));
return e}).then(function(){})},lYa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return q4(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.q(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(q4(c.index("byChildEntityKey"),f.childEntityKey));return g.Xs.all(e)}).then(function(d){var e=[];
d=g.q(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},k5=function(a,b){g.G.call(this);
this.token=a;this.u=b;this.j=[];a=new g.C.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.Ms());a.onmessage=this.B.bind(this);this.channel=a},l5=function(a,b,c){var d,e,f,k;
return g.B(function(l){if(1==l.j)return g.A(l,dYa(a.token),2);if(3!=l.j)return d=l.u,g.A(l,g.et(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new eYa(m,a.u);return c(e)}),3);
f=l.u;e&&(k=e.B,0<Object.keys(k).length&&(a.channel.postMessage(k),mYa(a,k)));return l.return(f)})},m5=function(a,b){a.j.push(b);
return function(){var c=a.j.indexOf(b);0<=c&&a.j.splice(c,1)}},n5=function(a,b,c){return l5(a,{mode:"readwrite",
Kc:!0},function(d){return g5(d,b,c)})},nYa=function(a,b){return l5(a,{mode:"readwrite",
Kc:!0},function(c){return h5(c,b,"offlineOrchestrationActionWrapperEntity")})},oYa=function(a,b){return l5(a,{mode:"readwrite",
Kc:!0},function(c){return i5(c,b,void 0)})},o5=function(a,b,c){return l5(a,{mode:"readonly",
Kc:!0},function(d){return d5(d,b,c)})},p5=function(a,b,c){return l5(a,{mode:"readonly",
Kc:!0},function(d){return e5(d,b,c)})},mYa=function(a,b){a=g.q(a.j);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},pYa=function(){var a,b,c;
return g.B(function(d){if(1==d.j)return g.va(d,2),g.A(d,g.wt(),4);if(2!=d.j){a=d.u;if(!a||!g.Ns()||"undefined"===typeof g.C.BroadcastChannel)return d.return();b=new ZXa;return d.return(new k5(a,b))}c=g.xa(d);c instanceof Error&&g.S(c);return d.return()})},r5=function(){q5||(q5=pYa());
return q5},qYa=function(a){var b;
a=null==(b=a.options)?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},rYa=function(a){var b;
return g.B(function(c){return 1==c.j?g.A(c,r5(),2):(b=c.u)?g.A(c,l5(b,"readwrite",function(d){for(var e={},f={},k=g.q(a),l=k.next();!l.done;f={yg:f.yg,Kr:f.Kr},l=k.next())f.yg=l.value,f.yg.entityKey&&qYa(f.yg)&&(f.Kr=g.Uf(f.yg.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.yg.type&&(l=function(m){return function(){return g5(d,m.yg.payload[m.Kr],m.Kr)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.yg.type&&(l=function(m){return function(){return i5(d,m.yg.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.yg.type&&(l=function(m){return function(){return jYa(d,m.yg.entityKey,m.yg.payload[m.Kr],m.Kr)}}(f)),l&&(e[f.yg.entityKey]=e[f.yg.entityKey]?e[f.yg.entityKey].then(l):l()));
return g.Xs.all(Object.values(e))}),0):c.return()})},sYa=function(a){var b;
return g.B(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.C0){var d=b,e={type:"ENTITY_LOADED"};void 0!==d&&(e.payload=d);g.C0.dispatch(e)}return g.A(c,rYa(b),2)}b.length=0;g.ua(c)})},tYa=function(a){return void 0!==a},s5=function(a,b){var c=b.nj;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;var d;a.isRefresh=null!=(d=c.isRefresh)?d:!1;var e;a.softErrorCount=null!=(e=c.transferRetryCount)?e:0;g.Gs("offlineTransferStatusChanged",a)},uYa=function(a){s5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},vYa=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
t5=function(){},u5=function(){},v5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.Ms("CacheStorage get")},wYa=function(){return g.B(function(a){if(void 0!==w5)return a.return(w5);
w5=new Promise(function(b){var c;return g.B(function(d){switch(d.j){case 1:return g.va(d,2),g.A(d,x5.open("test-only"),4);case 4:return g.A(d,x5.delete("test-only"),5);case 5:g.wa(d,3);break;case 2:if(c=g.xa(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.ua(d)}})});
return a.return(w5)})},z5=function(){return g.B(function(a){if(1==a.j)return g.A(a,wYa(),2);
if(!a.u)return a.return(void 0);y5||(y5=new u5);return a.return(y5)})},xYa=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,z5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},yYa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,z5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},zYa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,z5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,c.addAll(a),0)})},A5=function(a){var b,c,d;
return 0<(null!=(d=null==(b=a.actionMetadata)?void 0:null==(c=b.retryScheduleIntervalsInSeconds)?void 0:c.length)?d:0)},B5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},C5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},F5=function(a,b,c,d){var e,f,k,l,m,n,p,r,t,v,x,y,z,E,I,J,N,aa,K,oa,na,za,Va,Ub;
return g.B(function(Ma){switch(Ma.j){case 1:return e=g.QK(a,"ytMainVideoEntity"),f=g.QK(a,"ytMainChannelEntity"),k=g.QK(a,"transfer"),g.A(Ma,l5(b,{mode:"readonly",Kc:!0},function(zb){return g.Xs.all([d5(zb,e,"ytMainVideoEntity"),d5(zb,f,"ytMainChannelEntity"),d5(zb,k,"transfer"),e5(zb,"ytMainChannelEntity"),e5(zb,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:l=Ma.u;m=g.q(l);n=m.next().value;p=m.next().value;r=m.next().value;t=m.next().value;v=m.next().value;x=n;y=p;z=r;E=t;I=v;if(!x&&!y){Ma.Za(3);break}J=x?D5(x.thumbnail):[];if(!y){N=[];Ma.Za(4);break}return g.A(Ma,AYa(y,E),5);case 5:N=Ma.u;case 4:return aa=N,g.A(Ma,yYa(J.concat(aa)),3);case 3:K=[];oa=g.QK(a,"ytMainDownloadedVideoEntity");na=g.q(I);for(za=na.next();!za.done;za=na.next())Va=za.value,Ub=g.PK(Va.key).entityId,Ub!==a||BYa(c,Va.actionProto)||K.push(Va.key);return g.A(Ma,l5(b,{mode:"readwrite",
Kc:!0},function(zb){var sc=K.map(function(Sd){return i5(zb,Sd)});
sc.push(i5(zb,oa,{pL:!0}));return g.Xs.all(sc)}),7);
case 7:CYa(z),E5(d,{entityKey:oa,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.ua(Ma)}})},EYa=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,l5(a,{mode:"readwrite",Kc:!0},function(p){var r=e5(p,"transfer"),t=e5(p,"offlineOrchestrationActionWrapperEntity");return g.Xs.all([r,t]).then(function(v){v=g.q(v);var x=v.next().value,y=v.next().value;v=DYa.map(function(J){return iYa(p,J)});
y=g.q(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var E="ytMainDownloadedVideoEntity"===g.PK(z.actionProto.entityKey).entityType,I="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;BYa(b,z.actionProto)||E&&(!E||I)||v.push(i5(p,z.key,{pL:!0}))}return g.Xs.all(v).then(function(){return x})})}),2);
d=n.u;e=g.q(d);for(f=e.next();!f.done;f=e.next())k=f.value,CYa(k),l=g.PK(k.key).entityId,m=g.QK(l,"ytMainDownloadedVideoEntity"),E5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,xYa(),0)})},BYa=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},CYa=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.PK(a.key).entityId;
s5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,nj:a})}},D5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.q(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},AYa=function(a,b){var c,d,e,f,k,l,m,n;
return g.B(function(p){c=D5(a.avatar);d=g.q(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(k=g.q(D5(f.avatar)),l=k.next();!l.done;l=k.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},G5=function(a){this.j=a},FYa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=new Map,d=g.q(b),e=d.next();case 2:if(e.done){n.Za(4);break}f=e.value;k=c;l=k.set;m=f;return g.A(n,a.B(f),5);case 5:l.call(k,m,n.u);e=d.next();n.Za(2);break;case 4:return n.return(c)}})},H5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},I5=function(a,b,c){g.Pv(new g.Ls("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.Pv(b)},J5=function(a,b,c){this.j=a;
this.Y=b;this.u=c},IYa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=b.entityKey;f=null==(d=b.actionMetadata)?void 0:null==(e=d.playbackDataActionMetadata)?void 0:e.isEnqueuedForExpiredStreamUrlRefetch;g.va(n,2);var p;var r=null!=(p=b.actionMetadata)&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.A(n,GYa(a,c,{isEnqueuedForExpiredStreamUrlRefetch:f,GQ:r}),4);case 4:return(k=n.u)?g.A(n,HYa(a,k,b),5):n.return(K5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 5:return n.return(K5(b,!0,k.orchestrationActions));case 2:return l=g.xa(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.Qs&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),I5("PDE handleAdd error"),n.return(K5(b,!1,void 0,m))}})},JYa=function(a,b){var c,d,e,f,k,l,m,n,p,r,t,v,x,y,z;
return g.B(function(E){switch(E.j){case 1:return c=b.entityKey,g.A(E,l5(a.j,{mode:"readonly",Kc:!0},function(I){var J=d5(I,c,"playbackData"),N=d5(I,g.QK(g.PK(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");I=d5(I,g.QK(g.PK(b.entityKey).entityId,"transfer"),"transfer");return g.Xs.all([J,N,I])}),2);
case 2:d=E.u;e=g.q(d);f=e.next().value;k=e.next().value;l=e.next().value;m=f;n=k;p=l;if(!m||!n)return E.return(K5(b,!0));r={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null==(v=p)?0:v.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.va(E,3);return g.A(E,GYa(a,c,{refreshData:r,GQ:t}),5);case 5:return(x=E.u)?g.A(E,HYa(a,x,b),6):E.return(K5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 6:return E.return(K5(b,
!0,x.orchestrationActions));case 3:return y=g.xa(E),z="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",y instanceof g.Qs&&"QUOTA_EXCEEDED"===y.type&&(z="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),E.return(K5(b,!1,void 0,z))}})},GYa=function(a,b,c){var d,e,f;
return g.B(function(k){d=g.lK();var l=a.Y,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.GQ,r={entityKey:b};m&&(r.refreshData=m);n&&(r.isExpiredStreamUrlRefetch=n);p&&(r.downloadParameters=p);e={context:g.xK(l),signatureTimestamp:19061,videos:[r]};f=g.KJ(KYa);return k.return(g.WH(d,e,f))})},HYa=function(a,b,c){var d;
return g.B(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.Za(2);d=g.PK(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.A(e,F5(d,a.j,c,a.u),2)}return g.A(e,sYa(b.frameworkUpdates.entityBatchUpdate),0)})},K5=function(a,
b,c,d){return new H5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",A5(a),c,d)},L5=function(){G5.apply(this,arguments)},MYa=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=A5(b),g.A(e,o5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.va(e,3);return g.A(e,LYa(a,b),5);case 5:g.wa(e,4);break;case 3:return g.xa(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},NYa=function(a,b){var c,
d;
return g.B(function(e){switch(e.j){case 1:return c=A5(b),g.A(e,o5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.va(e,3);return g.A(e,LYa(a,b,!0),5);case 5:g.wa(e,4);break;case 3:return g.xa(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},LYa=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return e=null==(d=b.actionMetadata)?void 0:d.transferEntityActionMetadata,l={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.yv(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null==(f=e)?void 0:f.maximumDownloadQuality,preferredAudioTrack:null==(k=e)?void 0:k.preferredAudioTrack,transferRetryCount:0,isRefresh:c},m=g.PK(l.key).entityId,g.A(n,l5(a.j,{mode:"readwrite",Kc:!0},function(p){var r=[];c&&r.push(i5(p,
g.QK(m,"offlineVideoStreams")));r.push(g5(p,l,"transfer"));return g.Xs.all(r)}),2);
s5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:m,nj:l});g.ua(n)})},OYa=function(a,b,c){return new g.XD(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},PYa=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},M5=function(a,b,c,d,e,f,k,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=k;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},N5=function(a){return{key:g.QK(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},QYa=function(){this.j=new Map},RYa=function(){O5||(O5=new QYa);
return O5},SYa=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0,can:void 0}},TYa=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.yv(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);b.can&&(a.can=b.can);g.Gs("flowEvent",a,void 0)},UYa=function(a,b,c){if(!a.action.entityKey)throw Error("entityKey is missing.");
var d=g.PK(a.action.entityKey);a={entityType:d.qU,entityId:d.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=b.j);c&&(a.additionalOrchestrationActions=c.map(function(e){return{orchestrationActionId:e.actionId}}));
return a},P5=function(a,b){var c={offlineOrchestrationContext:UYa(a)};
b=SYa(b,c);TYa(RYa(),b,a.rootActionId)},Q5=function(a,b,c){c=void 0===c?[]:c;
b={offlineOrchestrationContext:UYa(a,b,c)};b=SYa(3,b);TYa(RYa(),b,a.rootActionId)},VYa=function(){this.actions=[]},WYa=function(a,b){b=g.q(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,P5(c,1),a.actions.push(c);a.actions.sort(a.j)},XYa=function(a,b){a=g.q(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},R5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.ma=b;this.X=c;this.D=d;this.j=new VYa;this.N=new g.Xt;this.C=new g.L(function(){e.retry()});
this.J=NaN;g.H(this,this.C);this.K=m5(this.u,this.Z.bind(this))},ZYa=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return e=new R5(a,b,c,d),g.A(f,YYa(e),2);e.B?Promise.resolve():S5(e);return f.return(e)})},S5=function(a){var b,c,d,e,f,k,l,m,n,p,r,t,v,x,y;
return g.B(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();$Ya(a.X,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.ma[b.entityType]){z.Za(2);break}a.B=void 0;return g.A(z,S5(a),3);case 3:return z.return();case 2:f=g.q(c);for(k=f.next();!k.done;k=f.next())l=k.value,P5(l,2);g.va(z,
4,5);return g.A(z,FYa(e,c.map(function(E){return E.action})),7);
case 7:m=z.u,n=g.q(c),k=n.next();case 8:if(k.done){z.Za(5);break}p=k.value;r=m.get(p.action);return g.A(z,aZa(a,p,r),9);case 9:k=n.next();z.Za(8);break;case 5:g.ya(z);a.B=void 0;g.Aa(z,6);break;case 4:return t=g.xa(z),I5("Orchestration error",t),g.va(z,12),g.A(z,bZa(a,c),14);case 14:g.wa(z,5);break;case 12:v=g.xa(z);I5("Orchestration retry error",v);x=g.q(c);for(k=x.next();!k.done;k=x.next())y=k.value,3>y.retryScheduleIndex&&WYa(a.j,[y]);z.Za(5);break;case 6:return g.A(z,S5(a),0)}})},aZa=function(a,
b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j){if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){k=void 0;try{k=null==(l=c.u)?void 0:l.map(function(p){return a.createAction(p,b)})}catch(p){return Q5(b,c),m={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},E5(a.D,m),I5("Orchestration subactions creation error",p),n.return()}Q5(b,c,k);return g.A(n,l5(a.u,{mode:"readwrite",Kc:!0},function(p){var r=[];if(k){var t=k.map(function(v){return N5(v)});
r.push(h5(p,t,"offlineOrchestrationActionWrapperEntity"))}t=N5(b);r.push(i5(p,t.key));return g.Xs.all(r)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return n.Za(0);
Q5(b,c);if(c.j&&3>b.retryScheduleIndex+1)return g.A(n,bZa(a,[b]),0);e=(null==(d=c)?0:d.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";f={entityKey:b.action.entityKey,failureReason:e};E5(a.D,f);I5("Orchestration result is not retryable, deleting action");return g.A(n,oYa(a.u,N5(b).key),0)}P5(b,4);g.ua(n)})},T5=function(a,b){var c,d,e,f,k,l,m,n,p,r,t,v;
return g.B(function(x){c=[];d=Infinity;e=4E3;f=g.q(b);for(k=f.next();!k.done;k=f.next())l=k.value,m=Number(l.enqueueTimeSec),n=cZa(m),p=l.retryScheduleIndex,r=null!=p&&0<p,0<n&&r?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.J)&&(a.J=d,a.C.start(e));a.N.Ne()||(t=c.length,c=c.filter(function(y){var z;y=(null==(z=y.actionProto)?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!dZa.includes(y)}),v=c.length<t,!a.C.isActive()&&v&&a.C.start(1));
0<c.length&&eZa(a,c);return g.A(x,a.B?Promise.resolve():S5(a),0)})},gZa=function(a){var b,c,d,e,f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,fZa(a),2);b=m.u;c=[];d=g.q(b);for(e=d.next();!e.done;e=d.next())f=e.value,k=g.PK(f.key),l=k.entityId,XYa(a.j,l)||c.push(f);return g.A(m,T5(a,c),0)})},cZa=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},bZa=function(a,b){var c,d,e;
return g.B(function(f){c=g.q(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var k=void 0,l=void 0,m=(null==(l=e.action)?void 0:null==(k=l.actionMetadata)?void 0:k.retryScheduleIntervalsInSeconds)||[1,2,4];k=1;e.retryScheduleIndex<m.length&&(k=m[e.retryScheduleIndex]);e.j=1E3*k+Date.now();e.retryScheduleIndex++}return g.A(f,hZa(a,b),0)})},YYa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,p5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.A(c,T5(a,b),0)})},eZa=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.PK(c.key),e=g.PK(c.actionProto.entityKey);c=new M5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&WYa(a.j,[c])})},fZa=function(a,b){var c;
return g.B(function(d){if(1==d.j)return g.A(d,p5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(tYa))})},hZa=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return N5(c)});
return nYa(a.u,b)},iZa=function(){this.j=void 0},kZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){c=b.videoId;d=b.V();e=!0;if(b.captionTracks.length)f=JXa(b),a.j=new g.zL(d,b,f);else if(b.Lb)k=g.$wa(b),a.j=new g.BL(d,b.Lb,c,k,b.xj),e=b.xj;else return l.return();return l.return(new Promise(function(m){var n;null==(n=a.j)||n.Pt(function(){return g.B(function(p){if(1==p.j)return g.A(p,jZa(a,c,e),2);m();g.ua(p)})})}))})},jZa=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,k,l,m,n,p,r,t,v,x,y,z;return g.B(function(E){switch(E.j){case 1:if(!a.j)return E.return();d=[];e=g.wL(a.j.u,c);f=[];k={};l=g.q(e.entries());for(m=l.next();!m.done;k={DC:k.DC},m=l.next())n=m.value,p=g.q(n),r=p.next().value,t=p.next().value,k.DC=r,v=t,x=a.j.qq(v,"json3"),y=g.Mr(x,{withCredentials:!0,format:"RAW"},3,500).then(function(I){return function(J){J={metadata:g.HD(e[I.DC]),trackData:J.xhr.responseText};f.push(J)}}(k)).Ch(function(I){I5("Caption fetch error",I)}),d.push(y);
return g.A(E,KXa(d),2);case 2:return g.va(E,3),g.A(E,OXa(b,f),5);case 5:g.wa(E,0);break;case 3:z=g.xa(E),I5("Caption DB transaction error",z),g.ua(E)}})},lZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,PXa(a),2);b=c.u;return c.return(!!b&&0<b.length)})},mZa=function(a,b){this.api=a;
this.j=b;this.logger=new g.sQ("woffle");this.u=!1;g.xD=this.api.V().S("html5_user_partitioned_ls")},nZa=function(a){return g.B(function(b){return b.return(QXa(a))})},oZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,g.Lva(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},U5=function(a,b){var c=g.AD(b);
if(1===c||0===c)return Promise.resolve();(c=pZa(a,b))&&c.stopVideo();a.B=0;return nZa(b)},V5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.AD(e)&&((b=pZa(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.BD(e,2),a.B=2,c?qZa(a.j):d&&rZa(a.j))},pZa=function(a,b){var c;
return(null==(c=a.player)?void 0:c.getVideoData().videoId)===b?a.player:null},sZa=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},W5=function(a){g.G.call(this);
this.j=a;this.u=m5(this.j,this.B.bind(this))},tZa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.QK(p,"transfer")});
return g.A(n,p5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(tYa).map(function(p){return g.PK(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);k=g.q(f);l=k.next();case 3:if(l.done){n.Za(5);break}m=l.value;return g.A(n,nZa(m),4);case 4:l=k.next();n.Za(3);break;case 5:return n.return(f)}})},vZa=function(a,b,c,d,e,f){var k,l,m;
return g.B(function(n){k="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(k="STREAM_TYPE_AUDIO_AND_VIDEO",I5("unexpected stream type")):c.video&&!c.audio?k="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(k="STREAM_TYPE_AUDIO");l=g.QK(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:k,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===k?Number(c.Yb()):void 0};return g.A(n,l5(a,{mode:"readwrite",Kc:!0},
function(p){var r=d5(p,l,"offlineVideoStreams"),t=d5(p,g.QK(b,"transfer"),"transfer");return g.Xs.all([r,t]).then(function(v){var x=g.q(v);v=x.next().value;x=x.next().value;if(!x)return i5(p,l).then(function(){});
v=[g5(p,uZa(v,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),v.push(g5(p,x,"transfer")));return g.Xs.all(v)})}),0)})},wZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.QK(b,"offlineVideoStreams"),g.A(l,o5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.q(d.streamsProgress);for(f=e.next();!f.done;f=e.next())k=f.value,k.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",k.numTotalBytes!==k.numBytesDownloaded&&(k.numBytesDownloaded=k.numTotalBytes);return g.A(l,n5(a,d,"offlineVideoStreams"),0)})},uZa=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var k=JSON.parse(e[f].formatStreamBytes);if(k.itag+";"+k.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},X5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.api=b;this.ya=c;this.xa=d;this.D=new g.Xt;this.C=new g.L(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.Ne()&&(3>(e.j.transferRetryCount||0)?V5(e.J,e.B,!1,!1):U5(e.J,e.B.videoDetails.videoId),e.Pq("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.X=0;this.va=new g.cA(this);this.K=m5(this.u,this.LS.bind(this));this.J=new mZa(b,this);this.Ia=new iZa;this.N=new W5(this.u);this.ma=this.D.Oa("publicytnetworkstatus-online",this.Xx.bind(this));this.Z=this.D.Oa("publicytnetworkstatus-offline",this.mZ.bind(this));g.H(this,this.va);this.va.T(b,"offlinetransferpause",this.nZ);this.Ea=g.XA(this.api.V().experiments,"web_player_transfer_timeout_threshold_ms")},xZa=function(a){g.B(function(b){if(1==b.j)b=g.A(b,NXa(),2);
else{var c=a.N;var d=g.zD();d=Object.keys(d);c=tZa(c,d);b=g.A(b,c,0)}return b})},Z5=function(a,b){b=void 0===b?!1:b;
var c;return g.B(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.A(d,yZa(a),2)}return 4!=d.j?(c=d.u,zZa(a.ya,!c),c&&a.D.Ne()?b?g.A(d,new Promise(function(e){g.Dr(e,1E3)}),4):d.Za(4):(!c&&a.j&&Y5(a),d.Za(0))):g.A(d,AZa(a,c),0)})},BZa=function(a){return g.B(function(b){if(1==b.j)return a.B?g.A(b,U5(a.J,a.B.videoDetails.videoId),3):b.Za(0);
Y5(a);g.ua(b)})},CZa=function(a,b){var c,d,e;
return g.B(function(f){switch(f.j){case 1:return g.va(f,2),(c=!!b.captionTracks.length||!!b.Lb)?g.A(f,lZa(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.A(f,kZa(a.Ia,b),5);case 5:g.wa(f,0);break;case 2:e=g.xa(f),I5("Caption downloading error",e,b.cotn),g.ua(f)}})},AZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){switch(l.j){case 1:return a.j=b,"TRANSFER_STATE_TRANSFERRING"===a.j.transferState&&(c=g.PK(a.j.key),s5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,nj:a.j})),g.A(l,$5(a),2);case 2:return d=null,g.va(l,3),g.A(l,DZa(a,b),5);case 5:d=l.u;a.B=d;g.wa(l,4);break;case 3:return e=g.xa(l),I5("error getting player response",e,b.cotn),g.A(l,a.Pq("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=
OYa(a.api.V(),b.cotn,d),g.A(l,CZa(a,f),7);case 7:return k=f,g.A(l,oZa(f.videoId),8);case 8:k.Sl=l.u;var m=a.J,n=b.maximumDownloadQuality;f.getPlayerResponse();g.BD(f.videoId,2);m.B=2;m.u=!1;var p;null==(p=m.player)||p.dispose();m.player=m.api.Mn(9,f);p={};g.lv(m.player,(p.localmediachange=m.nB,p.signatureexpired=m.SG,p.statechange=m.aX,p),m);n=sZa(n);m.S("hoffle_lmqf_killswitch")||(n=g.Hx(n,n,!0,"m"),g.mMa(m.player,n,!1));g.JP(m.player,!1);a6(a);g.ua(l)}})},yZa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,p5(a.u,"transfer"),2);b=d.u;c=b.filter(EZa).sort(FZa);return 0===c.length?d.return():d.return(c[0])})},$5=function(a){return g.B(function(b){a6(a);
return g.A(b,b6(a,"TRANSFER_STATE_TRANSFERRING"),0)})},qZa=function(a){var b;
g.B(function(c){if(1==c.j)return a.C.stop(),g.A(c,b6(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.PK(a.j.key);uYa({videoId:b.entityId,nj:a.j});Y5(a);Z5(a);g.ua(c)})},rZa=function(a){g.B(function(b){if(1==b.j)return a.C.stop(),g.A(b,b6(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
Y5(a);g.ua(b)})},GZa=function(a){var b,c,d;
g.B(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.Za(2);break}b=OYa(a.api.V(),a.j.cotn,a.B);return g.A(e,CZa(a,b),2);case 2:return g.A(e,b6(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.PK(a.j.key),d=c.entityId,g.A(e,wZa(a.u,d),5);case 5:s5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,nj:a.j}),Y5(a),Z5(a),g.ua(e)}})},HZa=function(a,b,c){var d;
g.B(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.Za(2);break}return g.A(e,$5(a),2);case 2:d=Date.now();if(!(1E3<d-a.X)){e.Za(4);break}a.X=d;return g.A(e,vZa(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:var f=Math.floor(c.bytesDownloaded/1024).toFixed();s5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",alreadyDownloadedKbytes:f,totalFetchedKbytes:f,totalContentKbytes:Math.floor(c.j/1024).toFixed()},
{videoId:b,nj:a.j});case 4:a6(a),g.ua(e)}})},IZa=function(a){var b=3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},JZa=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.B(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.A(e,b6(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);E5(a.xa,{entityKey:a.j.key,failureReason:c});d=g.PK(a.j.key).entityId;var f={videoId:d,nj:a.j},k=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};k&&(l.transferFailureReason=k,l.failureReason=vYa(k));s5(l,f);g.ua(e)})},b6=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.va(f,2),g.A(f,KZa(a,function(k){return c?e5(k,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.q(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.q(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return h5(k,l.filter(function(r){return!!r}),"offlineVideoStreams")}):g.Xs.resolve(void 0)}),4);
if(2!=f.j)return g.wa(f,0);e=g.xa(f);return e instanceof g.Qs&&"QUOTA_EXCEEDED"===e.type?g.A(f,a.Pq("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.Za(0)})},KZa=function(a,b){var c;
return g.B(function(d){if(!a.j)return d.return();c=a.j;return g.A(d,l5(a.u,{mode:"readwrite",Kc:!0},function(e){var f=[g5(e,c,"transfer")];b&&f.push(b(e));return g.Xs.all(f)}),0)})},Y5=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},DZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.PK(b.key),d=c.entityId,e=g.QK(d,"playbackData"),g.A(l,o5(a.u,e,"playbackData"),2);f=l.u;if(null==(k=f)?0:k.playerResponseJson)return l.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},a6=function(a){a.C.start(a.Ea||6E4)},EZa=function(a){return void 0!==c6[a.transferState]},FZa=function(a,b){var c=c6[a.transferState],d=c6[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},LZa=function(a){var b,c,d,e,f,k,l,m,n,p,r,t,v,x,y,z,E;
return g.B(function(I){if(1==I.j)return g.A(I,l5(a,{mode:"readonly",Kc:!0},function(J){return e5(J,"playbackData").then(function(N){var aa=N.map(function(oa){return oa.transfer}).filter(function(oa){return!!oa}),K=N.map(function(oa){return oa.offlineVideoPolicy}).filter(function(oa){return!!oa});
aa=e5(J,"transfer",aa);K=e5(J,"offlineVideoPolicy",K);return g.Xs.all([aa,K]).then(function(oa){var na=g.q(oa);oa=na.next().value;na=na.next().value;return[N,oa,na]})})}),2);
b=I.u;c=g.q(b);d=c.next().value;e=c.next().value;f=c.next().value;k=d;l=e;m=f;n={};p={};r=g.q(l);for(t=r.next();!t.done;t=r.next())(v=t.value)&&(n[v.key]=v);x=g.q(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);E=k.map(function(J){var N=n[J.transfer],aa=p[J.offlineVideoPolicy];J=g.PK(aa.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===aa.action){var K="OFFLINE_VIDEO_STATE_DISABLED";aa.expirationTimestamp&&Number(aa.expirationTimestamp)<Date.now()/1E3&&(K="OFFLINE_VIDEO_STATE_EXPIRED");
aa=K}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===aa.action)aa="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null==N?void 0:N.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":K="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":K="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":K="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":K="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":K=
"OFFLINE_VIDEO_STATE_PLAYABLE";break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":K="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:K="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===K)switch(null==N?void 0:N.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":K="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":K="OFFLINE_VIDEO_STATE_STREAMS_MISSING";
break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":K="OFFLINE_VIDEO_STATE_NETWORK_ERROR"}aa=K}J={id:J,videoState:aa};if(null==N?0:N.cotn)J.cotn=N.cotn;if(null==N?0:N.maximumDownloadQuality)J.selectedVideoQuality=null==N?void 0:N.maximumDownloadQuality;return J});
return I.return({offlineVideos:E})})},MZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,LZa(a),2);b=c.u;g.Gs("offlineStateSnapshot",b);g.ua(c)})},d6=function(a){g.G.call(this);
this.api=a;"undefined"!==typeof g.C.BroadcastChannel&&(this.j=new g.C.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.Ms()),this.j.onmessage=this.B.bind(this),this.u=new g.C.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.Ms()),this.u.onmessage=this.C.bind(this))},E5=function(a,b){a.api.Pa("onOfflineOperationFailure",b);
var c;null==(c=a.j)||c.postMessage(b)},NZa=function(){this.locks=navigator.locks},OZa=function(){try{var a=g.La("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.C.localStorage&&g.C.localStorage.getItem("noop"),a=new NZa,g.Ka("ytglobal.locks_",a,void 0),a}catch(d){}},QZa=function(a,b,c,d){var e=this;
this.N=a;this.X=b;this.visibility=c;this.S=d;this.C=this.J=this.D=this.u=this.j=!1;this.K=new g.L(function(){PZa(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.Oe()})},RZa=function(a){if(!a.u&&!a.j){var b=OZa();
if(b){a.u=!0;var c=g.Ms("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f,k;return g.B(function(l){switch(l.j){case 1:return g.va(l,2),a.B=new g.Sj,a.j=!0,a.u=!1,g.A(l,a.N(),4);case 4:return g.A(l,a.B.promise,5);case 5:g.wa(l,0);break;case 2:d=g.xa(l),(null==(f=(e=a).S)?0:f.call(e,"wo_relinquish_leadership_on_lock_request_error"))||PZa(a),d instanceof Error&&(k=d,k.args=[{name:"WoLockManagerError",xB:d.name}],g.S(k)),g.ua(l)}})})}}},SZa=function(a){a.j&&(a.C=
!0,e6(a))},$Ya=function(a,b){a.j&&(a.D=b,e6(a))},zZa=function(a,b){a.j&&(a.J=b,e6(a))},e6=function(a){a.J&&a.D&&a.C&&a.visibility.isBackground()?g.xp(a.K,6E4):a.K.stop()},PZa=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.X()},f6=function(a,b){var c=this;
this.Y=a;this.api=b;this.N=new g.Xt;this.u=new QZa(function(){return TZa(c)},function(){UZa(c)},this.api.Bo(),this.api.S.bind(this.api));
this.B=new d6(this.api);this.C=new g.Sj;RZa(this.u)},TZa=function(a){return g.B(function(b){a.api.Pa("onOrchestrationBecameLeader");
a.j&&a.D||VZa(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.A(b,c,0)})},VZa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return g.A(e,r5(),2);if(3!=e.j){b=e.u;if(!b)return I5("PES is undefined"),e.return();a.j=new X5(b,a.api,a.u,a.B);c=a.kF(b);d=a;return g.A(e,ZYa(b,c,a.u,a.B),3)}d.D=e.u;return g.A(e,WZa(a),0)})},WZa=function(a){var b;
return g.B(function(c){switch(c.j){case 1:if(!a.j)return I5("transferManager is undefined"),c.return();if(a.j.j){c.Za(2);break}return g.A(c,Z5(a.j),2);case 2:return g.A(c,a.Tx(),4);case 4:return a.J=g.Er(function(){a.Tx()},9E5),g.Wr(g.Yr(),function(){a.j&&xZa(a.j)}),g.A(c,r5(),5);
case 5:return b=c.u,g.A(c,MZa(b),6);case 6:SZa(a.u),g.ua(c)}})},UZa=function(a){var b,c;
g.B(function(d){if(1==d.j)return a.j||a.D?g.A(d,a.C.promise,2):d.return();void 0!==a.J&&(g.Gr(a.J),a.J=void 0);null==(b=a.j)||b.dispose();a.j=void 0;null==(c=a.D)||c.dispose();a.D=void 0;a.api.Pa("onOrchestrationLostLeader");a.C=new g.Sj;g.ua(d)})},XZa=function(){var a,b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return g.A(k,r5(),2);case 2:a=k.u;if(!a)return k.return([]);b=Date.now()/1E3;return g.A(k,p5(a,"offlineVideoPolicy"),3);case 3:c=k.u,d=g.q(c),e=d.next();case 4:if(e.done){k.Za(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){k.Za(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.A(k,n5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();k.Za(4);break;case 6:return k.return(c.map(function(l){return l.key}))}})},g6=
function(a,b,c,d,e){var f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,r5(),2);f=m.u;if(!f)return m.return([]);k=b.map(function(n){var p=g.QK(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign({},PYa(),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new M5(c,n,p);return N5(n)});
l=nYa(f,k);RZa(a.u);return m.return(l)})},ZZa=function(a){var b,c,d,e;
return g.B(function(f){if(1==f.j)return b=g.lK(),c=RXa(a),d=g.KJ(YZa),g.A(f,g.WH(b,c,d),2);e=f.u;if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return f.return(e.videos.map(function(k){return k.offlineVideoData}))})},h6=function(a,b,c){this.j=a;
this.Y=b;this.u=c},b_a=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return c=A5(b),d=g.PK(b.entityKey),e=d.entityId,g.va(m,2),g.A(m,$Za(a,e),4);case 4:g.wa(m,3);break;case 2:return f=g.xa(m),k="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.Qs&&"QUOTA_EXCEEDED"===f.type&&(k="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,k));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=a_a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},c_a=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return c=A5(b),d=g.PK(b.entityKey),e=d.entityId,g.A(n,o5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.va(n,3);return g.A(n,$Za(a,e,f.addedTimestampMillis),5);case 5:k=a_a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.wa(n,4);break;case 3:return l=g.xa(n),l instanceof Error&&"No data"===l.message?g.A(n,F5(e,a.j,b,a.u),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.Qs&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,k?[k]:void 0))}})},d_a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=A5(b),g.va(e,2),d=g.PK(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,EYa(a.j,b,a.u),5):g.A(e,F5(d,a.j,b,a.u),5);case 5:g.wa(e,3);break;case 2:return g.xa(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},$Za=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return g.A(n,ZZa([b]),2);case 2:return d=n.u,e=d[0],g.A(n,e_a(a,e,c),3);case 3:f=n.u;k=f.videoEntity;l=f.channelEntity;g.va(n,4);var p=D5(k.thumbnail),r=D5(l.avatar);return g.A(n,zYa(p.concat(r)),6);case 6:g.wa(n,0);break;case 4:m=g.xa(n);if(!a.Y.S("woffle_disable_thumbnails"))throw m;g.ua(n)}})},e_a=function(a,b,c){var d,e,f,k,l;
return g.B(function(m){if(1==m.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.QK(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};k={id:g.QK(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):
void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.QK(b.videoId,"ytMainDownloadedVideoEntity"),video:k.id,playbackData:g.QK(b.videoId,"playbackData"),offlineVideoPolicy:g.QK(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return g.A(m,l5(a.j,{mode:"readwrite",Kc:!0},function(n){var p=g5(n,f,"ytMainChannelEntity"),r=g5(n,k,"ytMainVideoEntity");n=g5(n,l,"ytMainDownloadedVideoEntity");
return g.Xs.all([p,r,n])}),2)}return m.return({videoEntity:k,
channelEntity:f,Lga:l})})},a_a=function(a,b,c){b=g.QK(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:f_a});return{actionType:a,entityKey:b,actionMetadata:c}},i6=function(){f6.apply(this,arguments);
this.K="ytMainDownloadedVideoEntity"},j6=function(){g.vL.apply(this,arguments)};
g.w(s4,r4);g.w(t4,s4);t4.prototype.fd=function(){return[]};
g.w(u4,s4);u4.prototype.fd=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.u(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.u(new Set(a)))};
g.w(v4,s4);v4.prototype.fd=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.u(new Set(a)))};
g.w(w4,r4);w4.prototype.fd=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.u(new Set(a)))};
g.w(x4,s4);x4.prototype.fd=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.q(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.u((new w4(c.value)).fd()));return[].concat(g.u(new Set(a)))};
g.w(y4,s4);y4.prototype.fd=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.u(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.u(new Set(a)))};
g.w(z4,s4);z4.prototype.fd=function(){return[]};
g.w(A4,s4);A4.prototype.fd=function(){return[]};
g.w(B4,s4);B4.prototype.fd=function(){return[]};
g.w(C4,s4);C4.prototype.fd=function(){return[]};
g.w(D4,s4);D4.prototype.fd=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);return[].concat(g.u(new Set(a)))};
g.w(E4,s4);E4.prototype.fd=function(){return[]};
g.w(F4,s4);F4.prototype.fd=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.u(this.j.fakeChildren));return[].concat(g.u(new Set(a)))};
g.w(G4,s4);G4.prototype.fd=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(H4,s4);H4.prototype.fd=function(){return[]};
g.w(I4,r4);I4.prototype.fd=function(){var a=[];this.j.playbackPosition&&a.push(this.j.playbackPosition);return[].concat(g.u(new Set(a)))};
g.w(J4,s4);J4.prototype.fd=function(){var a=[];this.j.owner&&a.push(this.j.owner);this.j.downloadState&&a.push(this.j.downloadState);this.j.userState&&a.push.apply(a,g.u((new I4(this.j.userState)).fd()));return[].concat(g.u(new Set(a)))};
g.w(K4,s4);K4.prototype.fd=function(){return[]};
g.w(L4,s4);L4.prototype.fd=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.u(new Set(a)))};
g.w(M4,s4);M4.prototype.fd=function(){return[]};
g.w(N4,s4);N4.prototype.fd=function(){return[]};
g.w(O4,s4);O4.prototype.fd=function(){return[]};
g.w(P4,s4);P4.prototype.fd=function(){return[]};
g.w(Q4,s4);Q4.prototype.fd=function(){return[]};
g.w(R4,s4);R4.prototype.fd=function(){return[]};
g.w(S4,s4);S4.prototype.fd=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.u(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(T4,s4);T4.prototype.fd=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.u(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.u(this.j.captionTrack));return[].concat(g.u(new Set(a)))};
g.w(U4,s4);U4.prototype.fd=function(){return[]};
g.w(V4,s4);V4.prototype.fd=function(){return[]};
g.w(W4,s4);W4.prototype.fd=function(){return[]};
var YZa=["offline"],KYa=["offline/get_playback_data_entity"],g_a={w1:"captionTrack",N8:"ytMainChannelEntity",O8:"ytMainDownloadedVideoEntity",P8:"ytMainVideoEntity",Gaa:"offlineOrchestrationActionWrapperEntity",Qaa:"offlineVideoPolicy",Raa:"offlineVideoStreams",Fba:"playbackData",gea:"transfer",Aca:"orchestrationWebSamplingEntity"};g.w(Y4,g.Ls);g.w($4,WXa);$4.prototype.B=function(a,b){b=Z4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
$4.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw SXa(1);var c=new TextDecoder;b=Z4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
g.w(a5,WXa);a5.prototype.B=function(a){return a};
a5.prototype.u=function(a){if(a instanceof Uint8Array)throw SXa(0);return a};
var $Xa={captionTrack:O4,channelHandle:t4,commerceCartListEntity:V4,downloadQualityPickerEntity:C4,fakeChannel:u4,fakePlaylist:v4,fakePlaylistEntryCollection:x4,fakeVideo:y4,fakeVideoDescription:z4,iconBadgeEntity:W4,liveChatPollStateEntity:B4,logoEntity:A4,mainPlaylistEntity:H4,mainVideoDownloadStateEntity:D4,mainVideoEntity:J4,markersVisibilityOverrideEntity:M4,offlineOrchestrationActionWrapperEntity:P4,offlineVideoPolicy:Q4,offlineVideoStreams:R4,offlineabilityEntity:E4,orchestrationWebSamplingEntity:F4,
pinnedProductEntity:N4,playbackData:S4,transfer:T4,videoPlaybackPositionEntity:U4,ytMainChannelEntity:K4,ytMainDownloadedVideoEntity:G4,ytMainVideoEntity:L4},c5;g.w(k5,g.G);k5.prototype.B=function(a){mYa(this,a.data)};
k5.prototype.ra=function(){this.channel.close()};
var q5;var x5=g.C.caches,w5,y5;t5.prototype.open=function(a){return x5.open(v5(a))};
t5.prototype.has=function(a){return x5.has(v5(a))};
t5.prototype.delete=function(a){return x5.delete(v5(a))};
t5.prototype.match=function(a,b){var c=this,d,e,f,k,l,m;return g.B(function(n){switch(n.j){case 1:return g.A(n,c.keys(),2);case 2:d=n.u,e=g.q(d),f=e.next();case 3:if(f.done){n.Za(5);break}k=f.value;return g.A(n,c.open(k),6);case 6:return l=n.u,g.A(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.Za(3);break;case 5:return n.return()}})};
g.w(u5,t5);u5.prototype.keys=function(){var a,b,c,d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return a=[],b=g.Ms("CacheStorage keys"),g.A(n,x5.keys(),2);c=n.u;d=g.q(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");k=-1===p?{xB:f}:{xB:f.substring(0,p),datasyncId:f.substring(p+1)};l=k.xB;m=k.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(g_a).map(function(a){return g_a[a]});
var DYa="captionTrack ytMainChannelEntity ytMainDownloadedVideoEntity ytMainVideoEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.w(J5,G5);J5.prototype.B=function(a){return B5(a)?IYa(this,a):C5(a)?JYa(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(L5,G5);L5.prototype.B=function(a){return B5(a)?MYa(this,a):C5(a)?NYa(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
L5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.B(function(f){switch(f.j){case 1:return c=A5(a),g.A(f,o5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.va(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.A(f,n5(b.j,d,"transfer"),5);case 5:e=g.PK(d.key).entityId;s5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,nj:d});g.wa(f,4);break;case 3:return g.xa(f),f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var dZa=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var O5;VYa.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.w(R5,g.G);R5.prototype.ra=function(){this.K&&this.K();g.G.prototype.ra.call(this)};
R5.prototype.createAction=function(a,b){var c=g.PK(a.entityKey).entityType,d=g.yv(16);return new M5(c,d,a,b.actionId,b.rootActionId)};
R5.prototype.Z=function(a){var b=this,c,d,e,f,k,l,m,n,p;return g.B(function(r){if(1==r.j){if(b.isDisposed())return r.return();d=null!=(c=a.offlineOrchestrationActionWrapperEntity)?c:new Set;e=[];f=g.q(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.PK(l),n=m.entityId,XYa(b.j,n)||e.push(l);return g.A(r,fZa(b,e),2)}p=r.u;return g.A(r,T5(b,p),0)})};
R5.prototype.retry=function(){var a=this;return g.B(function(b){return g.A(b,gZa(a),0)})};g.h=mZa.prototype;g.h.aX=function(a){var b=this,c,d,e;return g.B(function(f){if(!g.V(a.state,128))return f.Za(0);var k=null==(c=a.state.getData())?void 0:c.errorCode,l=null==(d=a.state.getData())?void 0:d.uH;e="net.retryexhausted"===k&&(null==l?0:l.includes("net.connect"))?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null==k?0:k.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.A(f,b.Pq(b.player.getVideoData().videoId,e),0)})};
g.h.Pq=function(a,b){var c=this;return g.B(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(V5(c,a,!1,!0),d.Za(0)):g.A(d,U5(c,a),3)}g.BD(a,4);return g.A(d,c.j.Pq(b),0)})};
g.h.nB=function(a){2===a.status?(a.status!==this.B&&($5(this.j),g.BD(a.videoId,2)),a.Mx&&HZa(this.j,a.videoId,a.Mx)):4===a.status?(U5(this,a.videoId),this.Pq(a.videoId,a.CA?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&GZa(this.j);this.B=a.status;this.api.Pa("localmediachange",{videoId:a.videoId,status:a.status})};
g.h.SG=function(){var a=this,b;return g.B(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.A(c,U5(a,b),2)}return g.A(c,a.j.SG(),0)})};
g.h.S=function(a){return this.api.V().S(a)};g.w(W5,g.G);W5.prototype.ra=function(){this.u&&this.u();g.G.prototype.ra.call(this)};
W5.prototype.B=function(a){var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){d=null!=(c=a.transfer)?c:new Set;e=[];f=g.q(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.PK(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.A(p,tZa(b,e),0)})};g.w(X5,g.G);g.h=X5.prototype;g.h.ra=function(){this.K&&this.K();this.N.dispose();this.C.dispose();this.ma&&g.mg(this.D.B,this.ma);this.Z&&g.mg(this.D.B,this.Z);g.G.prototype.ra.call(this)};
g.h.nZ=function(a){var b=this,c,d;return g.B(function(e){if(1==e.j)return c=g.QK(a,"transfer"),b.j&&c===b.j.key?(V5(b.J,b.B,!0),b.C.stop(),e.Za(0)):g.A(e,l5(b.u,{mode:"readwrite",Kc:!0},function(f){return d5(f,c,"transfer").then(function(k){if(k&&"TRANSFER_STATE_COMPLETE"!==k.transferState&&"TRANSFER_STATE_FAILED"!==k.transferState)return k.transferState="TRANSFER_STATE_PAUSED_BY_USER",g5(f,k,"transfer").then(function(){return k})})}),3);
(d=e.u)&&uYa({videoId:a,nj:d});g.ua(e)})};
g.h.mZ=function(){this.j&&this.B&&V5(this.J,this.B,!1);this.C.stop()};
g.h.Xx=function(){this.j?AZa(this,this.j):Z5(this)};
g.h.LS=function(a){var b=this,c;return g.B(function(d){switch(d.j){case 1:if(!b.j){d.Za(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.Za(3);break}c=b;return g.A(d,o5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.Za(3);break}return g.A(d,BZa(b),3);case 3:if(b.j)return d.return();case 2:return g.A(d,Z5(b),0)}})};
g.h.Pq=function(a,b){var c=this,d,e;return g.B(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var k=!1;break a;default:k=!0}return k&&IZa(c)?g.A(f,b6(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.A(f,JZa(c,a),3)}3!=f.j&&(d=g.PK(c.j.key).entityId,s5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,nj:c.j}));Y5(c);e=Z5(c,!0);b&&b(e);g.ua(f)})};
g.h.SG=function(a){var b=this,c,d,e,f,k,l;return g.B(function(m){if(1==m.j)return IZa(b)?g.A(m,b6(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.A(m,JZa(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.PK(b.j.key).entityId,s5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,nj:b.j}),d=PYa(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.QK(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},k=N5(new M5("playbackData",c,f)),g.A(m,n5(b.u,k,"offlineOrchestrationActionWrapperEntity"),3);Y5(b);l=Z5(b,!0);a&&a(l);g.ua(m)})};
var k6={},c6=(k6.TRANSFER_STATE_TRANSFERRING=1,k6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,k6);g.w(d6,g.G);d6.prototype.B=function(a){this.api.Pa("onOfflineOperationFailure",a.data)};
d6.prototype.C=function(a){this.api.ea("offlinetransferpause",a.data)};
d6.prototype.ra=function(){var a;null==(a=this.j)||a.close();var b;null==(b=this.u)||b.close()};NZa.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};QZa.prototype.Oe=function(){this.j&&e6(this)};g.h=f6.prototype;g.h.kF=function(a){var b={};return b.playbackData=new J5(a,this.Y,this.B),b.transfer=new L5(a),b};
g.h.isOrchestrationLeader=function(){return this.u.j};
g.h.iH=function(a){var b=this.B;b.api.ea("offlinetransferpause",a);var c;null==(c=b.u)||c.postMessage(a)};
g.h.Xx=function(a){var b,c;return g.B(function(d){if(1==d.j)return g.A(d,r5(),2);b=d.u;if(!b)return d.return();c=g.QK(a,"transfer");return g.A(d,l5(b,{mode:"readwrite",Kc:!0},function(e){return d5(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",g5(e,f,"transfer").then(function(){s5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,nj:f});return g.Xs.resolve(null)})):
g.Xs.resolve(null)})}),0)})};
g.h.Tx=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){if(1==p.j)return b.N.Ne()?g.A(p,r5(),2):p.return(XZa());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.A(p,p5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];k=g.q(e);for(l=k.next();!l.done;l=k.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.PK(m.key).entityId,f.push(n));return f.length?p.return(g6(b,f,b.K,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.h.deleteAll=function(){return g6(this,["!*$_ALL_ENTITIES_!*$"],this.K,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.w(h6,G5);h6.prototype.B=function(a){return B5(a)?b_a(this,a):C5(a)?c_a(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&a.entityKey?d_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var f_a=[10];g.w(i6,f6);i6.prototype.kF=function(a){var b=f6.prototype.kF.call(this,a);b.ytMainDownloadedVideoEntity=new h6(a,this.Y,this.B);return b};g.w(j6,g.vL);g.h=j6.prototype;g.h.create=function(){var a=this.player.V();g.ZC(a)&&(this.j=new i6(a,this.player))};
g.h.ai=function(){return!1};
g.h.vH=function(a,b,c,d){var e=this;return g.B(function(f){return e.j?f.return(g6(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.h.deleteAll=function(){return this.j.deleteAll()};
g.h.Tx=function(a){return this.j.Tx(a)};
g.h.iH=function(a){this.j.iH(a)};
g.h.Xx=function(a){return this.j.Xx(a)};
g.h.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.uL("offline",j6);})(_yt_player);
